# data prep
library(raster)
library(rgdal)
library(spatial.tools)
library(tcltk)
library(r2excel)
library(splitstackshape)
library(stringr)
library(plyr)
library(ggplot2)
library(grid)
library(tiff)
library(RColorBrewer)
library(rasterVis)
library(reshape2)
library(foreign)
library(lattice)
library(latticeExtra)

# fire
library(dismo)
library(maptools)
library(ENMeval)
library(utils)

# biodiversity
library(rgeos)
library(DBI)
library(plyr)
library(tiff)
library(magick)
library(vegan)
library(RSQLite)
library(SDMTools)
library(dplyr)
library(gridExtra)
library(pracma)
library(zoo)